model: "base_fc"
loss_method: "cross-entropy"
opt_method: "Adam"
batch_size: 16
img_shape: [800,800]
epochs: 100
num_classes: 19
CUDA_DIX: [0,1]
lr: 0.01
GPU: True
backbone: "resnet50"
save_best: True
retrain: False
