model: "Deeplabv3"
loss_method: "cross-entropy"
opt_method: "Adam"
batch_size: 16
img_shape: [512,512]
epochs: 100
num_classes: 34
lr: 0.001
GPU: True
backbone: "resnet50"
save_best: True
retrain: False
