model: "Deeplabv3"
loss_method: "cross-entropy"
opt_method: "Adam"
batch_size: 4
img_shape: [800,800]
epochs: 100
num_classes: 19
lr: 0.001
GPU: True
backbone: "resnet50"
save_best: True
retrain: True
